### ISSUE TITLE
missing 08_jason_moiron.md

### ISSUE THREAD

**Issue by natebrennand** [peggyl/gotham-go#3]
I think you forgot to commit the file?

**Comment by natebrennand** [comment]
Also in the README: `s/11_nick_sullivan.nd/11_nick_sullivan.md`

**Comment by peggyl** [comment]
Thanks, Nate'! 

There was a last-minute replacement speaker for talk #8, and I meant to verify spelling of his name and find Twitter handle. Updating now...
